on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [ 20 ]
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: 🏗️ Build
        run: |
          pnpm run -r build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./packages/site/build/
          server-dir: www/